apiVersion: v1
kind: Namespace
metadata:
  name: loki-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: loki-stack
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.45.0
        ports:
        - containerPort: 16686 # Jaeger UI port
        - containerPort: 6831  # UDP port for traces
        - containerPort: 6832  # UDP port for traces
        - containerPort: 14268 # HTTP port for traces
        - containerPort: 14250 # GRPC port for traces
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: loki-stack
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: http
    protocol: TCP
    port: 16686
    targetPort: 16686
  - name: grpc
    protocol: TCP
    port: 14250
    targetPort: 14250
  - name: thrift
    protocol: TCP
    port: 14268
    targetPort: 14268
  - name: udp1
    protocol: UDP
    port: 6831
    targetPort: 6831
  - name: udp2
    protocol: UDP
    port: 6832
    targetPort: 6832
  type: ClusterIP
